url: https://superprofe.asesoreducativo.mx/
baseurl: 

# Site settings
title: Súper Profe
email: superprofe@asesoreducativo.mx
description: "Conviértete en Súper Profe con todas las habilidades necesarias para el mundo híbrido digital-presencial."


# Team names, titles and social links
people:
- name: Carlos Chee
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll
# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Mexicalim, Baja California, MX

# Build settings
markdown: kramdown
permalink: pretty